config/routes.rb
Rails.application.routes.draw do
  get 'reviews/new'
  devise_for :users
  root to: "pages#home"

  get 'dashboard', to: "pages#dashboard"
  get 'dreamsdashboard', to: "pages#dreamsdashboard"
  get 'bookingsdashboard', to: "pages#bookingsdashboard"


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :dreams do
    resources :bookings, only: [:create]
  end

  resources :bookings
  patch 'accept/:id', to: "bookings#accept", as: :accept
  patch 'decline/:id', to: "bookings#decline", as: :decline



  resources :dreams do
    resources :reviews, only: [:create, :new]
  end
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  has_many :reviews

  belongs_to :user
  belongs_to :dream

  validates :start_date, presence: true
  validates :end_date, presence: true

  def total_price
    return 0 unless end_date.present? && start_date.present? && self.dream.price_per_night.present?

    (self.end_date - self.start_date).to_i * self.dream.price_per_night
  end

  def number_of_nights
    return 0 unless end_date.present? && start_date.present?

    (self.end_date - self.start_date).to_i
  end
end

app/models/dream.rb
class Dream < ApplicationRecord
  has_many :bookings
  has_many :reviews, dependent: :destroy
  belongs_to :user

  has_many_attached :photos

  AGES = [12, 16, 18]

  validates :title, presence: true, uniqueness: true
  validates :description, presence: true
  validates :price_per_night, presence: true
  CATEGORIES = ["Action", "Success", "Lust", "Dreamy", "Adventure", "Travel", "Fantasy", "Time traveler", "Nightmare"]
  validates :category, inclusion: {in: CATEGORIES}
  validates :age_limit, presence: true, inclusion: {in: AGES}
  ROLES = (1..10).to_a
  validates :number_of_roles, inclusion: {in: ROLES}

  scope :by_category, ->(category) { where(category: category) if category.present? }
  scope :recent, -> { order(created_at: :desc) }
  scope :best_rated, -> { joins(:reviews).group('dreams.id').order('AVG(reviews.rating) DESC') }

  def average_rating
    return 0 if self.reviews.empty?
    ratings = self.reviews.pluck(:rating)
    ratings.sum.to_f / ratings.size
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :dream
  belongs_to :user
  RATINGS = (1..5)

  validates :rating, presence: true, inclusion: { in: 1..5, message: "must be between 1 and 5" }
  validates :comment, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  has_many :dreams
  has_many :bookings
  has_many :reviews

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  skip_before_action :authenticate_user!, only: [:home]

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:nickname])
  end

  def home
    # Define what 'home' should do here.
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only:[:show, :accept, :decline]
  before_action :set_dream, only:[:create]

  def show
  end

  def new
    @dream = Dream.find(params[:dream_id]) # Charge le Dream
    @booking = @dream.bookings.new        # Prépare une nouvelle Booking associée
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.dream = @dream
    @booking.user = current_user
    @booking.status = nil
    if @booking.save
      redirect_to bookingsdashboard_path
    else
      flash.now[:alert] = "Erreur lors de la création de la réservation."

    end
  end


  def accept
    @booking.status = true
    @booking.save!
    redirect_to dreamsdashboard_path
  end

  def decline
    @booking.status = false
    @booking.save!
_    redirect_to dreamsdashboard_path
  end

  def update
  end

  def edit
  end

  def destroy
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :dream_id, :user_id)
  end

  def set_dream
    @dream = Dream.find(params[:dream_id])
  end
end

app/controllers/dream_controller.rb
class DreamController < ApplicationController
before_action :set_dream, only: [:show]

  def index
    @dreams = Dream.all
  end

  def show
  end

  def new
    @dream = Dream.new
  end

  def create
    @dream = Dream.new(dream_params)
    if dream.save
      redirect_to dream_path(@dream)
    else
      render :new, :unprocessable_entity
    end
  end

  def update
  end

  def edit
  end

  def destroy
  end

  private

  def set_dream
    @dream = Dream.find(params[:id])
  end

  def dream_params
    params.require(:dream).permit(:title, :description, :price_per_night, :category, :age_limit, :number_of_roles)
  end

end

app/controllers/dreams_controller.rb
class DreamsController < ApplicationController
before_action :set_dream, only: [:show, :edit, :update, :destroy]

  def index
    @categories = Dream::CATEGORIES
    @dreams = Dream.all

    # Filtrage par recherche
    if params[:query].present?
      sql_subquery = <<~SQL
        dreams.title ILIKE :query
        OR dreams.description ILIKE :query
        OR dreams.category ILIKE :query
      SQL
      @dreams = @dreams.joins(:user).where(sql_subquery, query: "%#{params[:query]}%")
    end

    # Filtrage par catégorie
    if params[:category].present?
      @dreams = @dreams.by_category(params[:category])
    end

    # Tri
    case params[:sort]
    when 'recent'
      @dreams = @dreams.recent
    when 'best_rated'
      @dreams = @dreams.best_rated
    end
  end

  def show
    @dream = Dream.find(params[:id])
    @booking = Booking.new
    @reviews = @dream.reviews

  end

  def new
    @dream = Dream.new
    @categories = Dream::CATEGORIES
    @ages = Dream::AGES
  end

  def create
    @dream = Dream.new(dream_params)
    @dream.user = current_user
    if @dream.save
      redirect_to dream_path(@dream)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @dream.update(dream_params)
      redirect_to dream_path(@dream)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def edit
  end

  def destroy
    @dream.destroy
    redirect_to dream_path, status: :see_other
  end

  private

  def set_dream
    @dream = Dream.find(params[:id])
  end

  def dream_params
    params.require(:dream).permit(:title, :description, :price_per_night, :category, :age_limit, :number_of_roles, photos: [])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def dashboard
    @user = current_user
    @total_dashboard = calculate_total_price
    @bookings = @user.bookings
    @dreams = Dream.where(user: current_user)
    @bookings_received = Booking.where(dream_id: @dreams.pluck(:id))
  end

  def dreamsdashboard
    @user = current_user
    @dreams = Dream.where(user: current_user)
    @bookings = Booking.where(dream_id: @dreams.pluck(:id))
  end

  def bookingsdashboard
    @user = current_user
    @bookings = @user.bookings
  end


private

  def calculate_total_price
    @user = current_user
    total = @user.dreams.sum do |dream|
      dream.bookings.where(status: true).sum(&:total_price)
    end
    total.round(0)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_dream, only: [:new, :create]

  def new
    @review = Review.new
    @ratings = Review::RATINGS
    @user = current_user
  end

  def create
    @review = Review.new(review_params)
    @review.dream = @dream
    @review.user_id = current_user.id
    if @review.save!
      redirect_to dream_path(@dream)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_dream
    @dream = Dream.find(params[:dream_id])
  end

  def review_params
    params.require(:review).permit(:comment, :rating, :user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dreams/_form.html.erb
<%= simple_form_for(dream, html: { class: 'form-container' }) do |f| %>
  <div class="mb-3">

    <%= f.input :title, placeholder: "Give a title to your dream...", input_html: { class: 'form-control' }, label: false %>
  </div>

  <div class="mb-3">
    <%= f.input :description, placeholder: "Tell us more about your dream...", input_html: { class: 'form-control' },label: false %>
  </div>

  <div class="mb-3">
    <%= f.input :category,
        collection: @categories,
        input_html: { class: 'form-control', data: { controller: "tom-select" } },label: 'Select a Category', prompt: 'Choose a category', label: false %>
  </div>

  <div class="mb-3">
    <%= f.input :price_per_night, placeholder: "Set your price", input_html: { class: 'form-control' }, label: false %>
  </div>

  <div class="mb-3">
      <%= f.input :age_limit,
      collection: @ages,
      input_html: { class: 'form-control', data: { controller: "tom-select" } },label: 'Set an age limit', prompt: 'Set an age limit', label: false %>

  </div>

  <div class="mb-3">
    <%= f.input :number_of_roles, placeholder: "How many characters you want", input_html: { class: 'form-control' }, label: false %>
  </div>

  <div class="mb-3">
    <%= f.input :photos, as: :file, placeholder: "Insert a mental picture of your dream", input_html: { class: 'form-control', multiple: true }, label: false %>
  </div>

  <div class="text-center">
    <%= f.submit "Submit", class: "btn btn-primary btn-lg rounded-5" %>
  </div>
<% end %>

app/views/dreams/edit.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h2>Modifier votre rêve</h2>
        <%= render "form", dream: @dream%>
      </div>
    </div>
  </div>
</div>

app/views/dreams/new.html.erb
<div class="container min-height py-5">
  <div class="row justify-content-center">
    <div class="col-12 col-md-8 col-lg-6">
      <div class="card shadow-lg border-0 rounded-4 mt-3">
        <div class="card-body p-5">
          <h2 class="text-center mb-2 fw-bold text-primary">Share Your Dream</h2>
          <p class="text-center text-muted mb-4">
            Share your unique dream and let others experience it.
          </p>
          <%= render "form", dream: @dream %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/dreams/show.html.erb
<div class="container mt-5">
  <div class="bg-transparent rounded-4 p-3 row align-items-start shadow">

    <!-- Left Column: Image/Carousel -->
    <div class="col-md-4 text-center">
      <% if @dream.photos.empty? %>
        <%= image_tag 'dreamdefault.png', class: 'card-img-top', alt: @dream.title %>
      <% else %>
        <div id="carouselExampleIndicators-<%= @dream.id %>" class="carousel slide" data-bs-ride="carousel"
     data-bs-interval="3000">
          <div class="carousel-indicators">
            <% @dream.photos.each_with_index do |photo, index| %>
              <li data-bs-target="#carouselExampleIndicators-<%= @dream.id %>"
                  data-bs-slide-to="<%= index %>"
                  class="<%= 'active' if index == 0 %>">
              </li>
            <% end %>
          </div>

          <div class="carousel-inner">
            <% @dream.photos.each_with_index do |photo, index| %>
              <div class="carousel-item <%= 'active' if index == 0 %>">
                <%= cl_image_tag photo.key, crop: :fill, class: 'd-block w-100 card-img-top rounded-4', alt: @dream.title %>
              </div>
            <% end %>
          </div>

          <!-- Carousel Controls -->
          <a class="carousel-control-prev" href="#carouselExampleIndicators-<%= @dream.id %>" role="button" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleIndicators-<%= @dream.id %>" role="button" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      <% end %>
      <p class="mt-3 text-muted">Hosted by: <strong><%= @dream.user.nickname %></strong></p>
    </div>

    <!-- Center Column: Dream Details -->
    <div class="col-md-6 d-flex flex-column justify-content-start">
      <h1 class="mb-3"><%= @dream.title %></h1>
      <h5 class="text-muted mb-2"><strong>Dream scenario:</strong></h5>
      <p class="text-muted"><em><%= @dream.description %></em></p>
        <div class="d-flex align-items-center">
          <i class="fa-solid fa-list"></i>
          <span class="m-2"><%= @dream.category %></span>
        </div>
        <div class="d-flex align-items-center">
          <i class="fa-solid fa-tag"></i>
          <span class="m-2"><%= @dream.price_per_night %>€ / night</span>
        </div>
        <div class="d-flex align-items-center">
          <i class="fa-solid fa-user"></i>
          <span class="m-2"><%= @dream.number_of_roles %></span>
        </div>
        <div class="col-md-2 text-center star-show">
          <% @dream.average_rating.round.times do %>
            <i class="fas fa-star star-yellow"></i>
        <% end %>
    </div>

    <!-- Right Column: Rating -->

  </div> <!-- End of row -->

<% if current_user != @dream.user %>
  <div class="container mt-5">
    <div class="row g-4">
      <!-- Reviews Section (Left) -->
      <div class="col-lg-8">
        <div class="bg-light shadow rounded-5 p-4">
          <% if @dream.reviews.empty? %>
            <small><em class="text-muted">Be the first one to review this dream</em></small>
          <% end %>
          <h4><%= @dream.reviews.count %> reviews for this dream</h4>
          <% @dream.reviews.each do |review| %>
            <div class="bg-white rounded-5 p-4 my-3 d-flex flex-column">
              <div class="d-flex justify-content-between w-100">
                <div class="d-flex star-show">
                  <% review.rating.times do %>
                    <i class="fas fa-star star-yellow"></i>
                  <% end %>
                  <!-- Added a margin to the right of the stars to create space -->
                  <small class="ml-2"><em class="text-muted"><%= distance_of_time_in_words_to_now(review.created_at) %> ago</em></small>
                </div>
                <small><em class="text-muted">by <%= review.user.nickname %></em></small>
              </div>
              <p class="mb-0"><%= review.comment %></p>
            </div>
          <% end %>
          <div class="my-2">
            <%= link_to "Give a review", new_dream_review_path(@dream), class: "btn btn-primary p-2 rounded" %>
          </div>
        </div>
      </div>




      <!-- Booking Form Section (Right) -->
      <div class="col-lg-4 d-flex flex-column justify-content-between">
        <div class="bookingy text-dark p-3 rounded-4 shadow">
          <%= render "formbooking", dream: @dream, booking: @booking %>
        </div>
      </div>
    </div>
  </div>
<% end %>



  <!-- Back to Dreams Button -->

</div>
 <div class="text-center mt-5">
          <%= link_to "Back to the Dreams", dreams_path, class: "btn btn-primary m-4" %>
        </div>

      
        <br>
        <br>

app/views/pages/dreamsdashboard.html.erb
<div class="container display">
  <!-- Navbar section -->
  <div class="d-flex justify-content-between align-items-center bg-gradient rounded-5 m-3 p-3 shadow">
    <div class="d-flex align-items-center">
    <%= link_to dashboard_path(@user), class: "d-flex align-items-center text-decoration-none" do %>
      <%= image_tag "https://cdn4.iconfinder.com/data/icons/evil-icons-user-interface/64/avatar-512.png", class: "rounded-circle", alt: "avatar", width: 70 %>
      <h3 class="ms-3"> <%= @user.nickname %> </h3>
      <% end %>
    </div>
    <div class="d-flex">
      <!-- Dreams Sold Card -->
      <div class="bg-transparent card_dash shadow-sm rounded-5 p-3 m-1">
        <div class="card_dash-body ">
          <h5 class="card_dash-title text-center"> <strong>Booking requests pending</strong></h5>
          <p class="card_dash-text fw-bold" id="total-earnings">
           <% total = @user.dreams.sum { |dream| dream.bookings.where(status: nil).count } %>
            <% if total.zero? %>
              <p style="font-weight: 200; font-size: 13px;"> <p class="text-center"> <em>No request pending</em></p>
            <% else %>
              <p style="font-weight: 300; font-size: 22px;"> <%= total %> </p>
            <% end %>
          </p>
        </div>
      </div>
      <div class="bg-transparent card_dash shadow-sm rounded-5 p-3 m-1">
        <div class="card_dash-body">
          <h5 class="card_dash-title"> <strong>Dreams Sold</strong></h5>
          <p class="card_dash-text fw-bold" id="reves-vendus">
            <% total_dream = @user.dreams.sum { |dream| dream.bookings.where(status: true).count } %>
            <% if total_dream.zero? %>
              <p class="text-center"> <em>No dreams sold yet</em></p>
            <% else %>
              <p class="text-center fw-bold">  <%= total_dream %> </p>
            <% end %>
        </div>
      </div>
      <!-- Total Earnings Card -->
      <div class="bg-transparent card_dash shadow-sm rounded-5 p-3 m-1">
        <div class="card_dash-body ">
          <h5 class="card_dash-title"> <strong>Total Earnings</strong></h5>
          <p class="card_dash-text fw-bold" id="total-earnings">
            <% total = @user.dreams.sum { |dream| dream.bookings.where(status: true).sum(&:total_price)} %>
            <% if total.zero? %>
              <p class="text-center"> <em>No dreams sold yet</em></p>
            <% else %>
              <p class="text-center fw-bold"> <%= total %> € </p>
            <% end %>
          </p>
        </div>
      </div>
    </div>
  </div>
  <!-- Main content section -->
  <div class="row text-center">
    <!-- Centered title -->

    <div class="col-12 mb-4">
      <% if @bookings.where(status: nil).empty? %>
      <h2 class="fw-bold">No new booking request... just sleep</h2>
      <% else %>
      <h2 class="fw-bold">Bookings requests for your dreams</h2>
      <% end %>
    </div>
    <!-- Dreams grid -->

<div class="col-12 d-flex flex-wrap justify-content-center">
      <% @bookings.each do |booking| %>
        <div class="col-6 col-sm-6 col-md-4 col-lg-3 mb-4">
          <%= link_to dream_path(booking.dream), class: "text-decoration-none" do %>
            <div class="card h-100 rounded-5 m-4" data-aos="zoom-in">
              <% if booking.dream.photos.attached? %>
                <%= cl_image_tag(booking.dream.photos[0].key, crop: :fill, class: 'card-img-top same-size rounded-top-5', alt: booking.dream.title) %>
              <% else %>
                <%= image_tag 'dreamdefault.png', class: 'card-img-top same-size rounded-top-5', alt: booking.dream.title %>
              <% end %>
              <div class="card-body text-center">
                <h4 class="card-title"><%= booking.dream.title %></h4>
                <div class="card-text">
                  <strong><%= booking.dream.price_per_night %>€</strong> /night
                  <br>
                 <% if booking.dream.reviews.empty? %>
                  3.0 <i class="fa fa-star"></i>
                <% else %>
                <%= booking.dream.average_rating %> <i class="fa fa-star"></i>
                <% end %>
                </div>
                <div class ='d-flex align-items-center mt-2 rounded justify-content-center'>
                <% if booking.status == true %>
                <p class = "text-center">Booking accepted ✅ </p>
                <% elsif booking.status == false %>
                <p class = "text-center">Booking rejected ❌ </p>
                <% else %>
                <%= link_to 'Accept', accept_path(booking), class: 'btn btn-success me-1', data: { turbo_method: "PATCH" }  %>
                <%= link_to 'Decline', decline_path(booking), class: 'btn btn-danger ms-1', data: { turbo_method: "PATCH" }  %>
                <% end %>
                </div>

              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>

      <div>
     <hr>
      </div>

    <div class="col-12 mb-4">
      <h2 class="fw-bold">Dreams created</h2>
    </div>

    <div class="col-12 d-flex flex-wrap justify-content-center">
      <% @dreams.each do |dream| %>
        <div class="col-12 col-sm-6 col-md-4 col-lg-3 mb-4">
          <%= link_to dream_path(dream), class: "text-decoration-none" do %>
            <div class="card h-100 rounded-5 m-2" data-aos="zoom-in">
              <% if dream.photos.attached? %>
                <%= cl_image_tag(dream.photos[0].key, crop: :fill, class: 'card-img-top same-size rounded-top-5', alt: dream.title) %>
              <% else %>
                <%= image_tag 'dreamdefault.png', class: 'card-img-top same-size', alt: dream.title %>
              <% end %>
              <div class="card-body text-center">
                <h4 class="card-title"><%= dream.title %></h4>
                <p class="card-text">
                  <strong><%= dream.price_per_night %>€</strong> per night
                  <br>
                 <% if dream.reviews.empty? %>
                  3.0 <i class="fa fa-star"></i>
                <% else %>
                <%= dream.average_rating %> <i class="fa fa-star"></i>
                <% end %>
                </p>
                <% if dream.bookings.empty? %>
                <p class="text-secondary">Number of bookings :</strong> 0 </strong></p>
                <p class="text-secondary">Total earnings : <strong>0€</strong></p>
                <% else %>
                <p class="text-secondary">Number of bookings : <strong><%= dream.bookings.count %></strong></p>
                <p class="text-secondary">Total earnings : <strong><%= dream.bookings.sum(&:total_price) %>€</strong></p>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>
<style>
  /* Make sure all images have the same size */
  .same-size {
    width: 100%;
    height: 250px; /* Adjust the height to whatever fits your design */
    object-fit: cover; /* Ensures the image fills the container without distortion */
  }
</style>

app/views/pages/home.html.erb
<%# <div class="mainbackground"> %>
  <div class="d-flex flex-column">
    <div class="hero position-relative text-white text-center d-flex align-items-center" style="background: url('homebckgrd.png');">
      <div class="container">
        <br>
        <br>
        <h1 class="titlebig mb-5 animate-text">Don't dream your life,</h1>
        <h1 class="titlebig2 mb-5 animate-text"> live your dreams</h1>
        <p class="lead"> Each of your nights is an opportunity to dream: choose the dreams you want to have!</p>
        <p class="lead"> Each of your dreams is a creation: share them on DreamDealer!</p>
        <%= link_to "Explore our dreams", dreams_path, class: "btn btn-light btn-lg rounded-pill px-4 shadow-sm m-5" %>
        <%= link_to "Share your dreams", new_dream_path, class: "btn btn-light btn-lg rounded-pill px-4 shadow-sm m-5" %>
        <br>
        <br>


        <div class="row my-5">
          <div class="col-md-4 mb-4">
            <div class="card h-100 shadow border-0" style="background: linear-gradient(135deg, rgba(255, 255, 255, 0.3), rgba(240, 240, 255, 0.3)); backdrop-filter: blur(10px); border-radius: 20px;">
              <div class="card-body text-center">
                <i class="fas fa-cloud-moon fa-3x text-primary mb-3"></i>
                <h5 class="card-title fw-bold">Personalized Dreams</h5>
                <p class="card-text text-muted">Choose from unique experiences tailored to your desires.</p>
              </div>
            </div>
          </div>

          <div class="col-md-4 mb-4">
            <div class="card h-100 shadow border-0" style="background: linear-gradient(135deg, rgba(255, 255, 255, 0.3), rgba(240, 240, 255, 0.3)); backdrop-filter: blur(10px); border-radius: 20px;">
              <div class="card-body text-center">
                <i class="fas fa-star fa-3x text-warning mb-3"></i>
                <h5 class="card-title fw-bold">Dream with your beloved</h5>
                <p class="card-text text-muted">Share your dreams and share your adventures with your friends.</p>
              </div>
            </div>
          </div>

          <div class="col-md-4 mb-4">
            <div class="card h-100 shadow border-0" style="background: linear-gradient(135deg, rgba(255, 255, 255, 0.3), rgba(240, 240, 255, 0.3)); backdrop-filter: blur(10px); border-radius: 20px;">
              <div class="card-body text-center">
                <i class="fas fa-dove fa-3x text-success mb-3"></i>
                <h5 class="card-title fw-bold">Global Discoveries</h5>
                <p class="card-text text-muted">Access dreams from all corners of the world.</p>
              </div>
            </div>
          </div>
        </div>


        <div>
          <div class="container mb-5">

            <%= link_to "Become a dreamer now", new_dream_path, class: "btn btn-light btn-lg rounded-pill px-4 shadow-sm m-5" %>
          </div>
          <br>
          <br>
          <br>
          <br>
        </div>



    </div>
  </div>
<%# </div> %>

app/views/reviews/create.html.erb
<h1>Review#create</h1>
<p>Find me in app/views/review/create.html.erb</p>

app/views/shared/_footer.html.erb
<div class="footer ">
  <div class="container">
    <div class="footer-links">
      <a href="#" class="me-3 text-dark"><i class="fab fa-github"></i></a>
      <a href="#" class="me-3 text-dark"><i class="fab fa-instagram"></i></a>

      <%= link_to "Categories", new_dream_path, class: "me-3 text-dark fw-bold" %>
      <%= link_to "Contact us", new_dream_path, class: "me-3 text-dark fw-bold" %>
      <%= link_to "Join us", new_dream_path, class: "text-dark fw-bold" %>
    </div>

    <div class="footer-copyright">
      <small>© 2024 DreamDealer. All rights reserved.</small>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon sticky-top">
  <div class="container-fluid">
    <%= link_to dreams_path, class: "navbar-brand d-flex align-items-center" do %>
      <%= image_tag "logo_dreamdealer.png", alt: "Logo", class: "m-2", height: "40" %>
      <span class="fw-bold text-primary">DreamDealer</span>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav m-3">
        <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Discover our dreams", dreams_path, class: "btn rounded nav-link text-decoration-none" %>
        </li>
        <li class="nav-item">
          <%= link_to "Share your dream", new_dream_path, class: "btn rounded nav-link text-decoration-none" %>
        </li>
        <li class="nav-item">
          <%= link_to "See my dashboard", dashboard_path(@user), class: "btn rounded nav-link text-decoration-none" %>
        </li>
        <% end %>
        <li class="nav-item dropdown">
          <a href="#" class="avatar m-3" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://cdn4.iconfinder.com/data/icons/evil-icons-user-interface/64/avatar-512.png", class: "avatar", alt: "dropdown menu" %>
          </a>
          <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <%= link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete }, class: "dropdown-item" %>
          </div>
        </li>
      </ul>
    </div>
  </div>
</div>